# Generated by Django 2.0.2 on 2018-02-18 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('user_image', models.ImageField(blank=True, default='/profile_images/pr_image.png', null=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
