# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 16:09
from __future__ import unicode_literals

import contact_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=230, null=True)),
                ('message', models.TextField()),
                ('captcha', models.TextField()),
            ],
        ),
    ]
