# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_auto_20180127_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='captcha',
        ),
    ]
