# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted_on']},
        ),
    ]
