# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180131_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
