# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name_plural': 'Comment Replies'},
        ),
    ]
