// AUTH ACTIONS
export const AUTHENTICATED = "AUTHENTICATED";
export const UNAUTHENTICATED = "UNAUTHENTICATED";
export const TESTING_TOKEN_REFRESH = "TESTING_TOKEN_REFRESH";

//CATEGORY ACTIONS
export const FETCHING_POSTS_FOR_CATEGORY = "FETCHING_POSTS_FOR_CATEGORY";
export const FETCH_POSTS_FOR_CATEGORY_SUCCESS =
  "FETCH_POSTS_FOR_CATEGORY_SUCCESS";
export const FETCH_POSTS_FOR_CATEGORY_FAILURE =
  "FETCH_POSTS_FOR_CATEGORY_FAILURE";

// CONTACTFORM ACTIONS
export const SUBMITTING_CONTACT_FORM = "SUBMITTING_CONTACT_FORM";
export const SUBMIT_CONTACT_FORM_SUCCESS = "SUBMIT_CONTACT_FORM_SUCCESS";
export const SUBMIT_CONTACT_FORM_FAILURE = "SUBMIT_CONTACT_FORM_FAILURE";

//NEWSLETTER ACTIONS
export const IS_SUBSCRIBING = "IS_SUBSCRIBING";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAILURE = "SUBSCRIBE_FAILURE";

// POST ACTIONS List
export const FETCHING_POSTS = "FETCHING_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

// POST ACTIONS Detail
export const FETCHING_POST = "FETCHING_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

// POST ARCHIVE Actions
export const FETCHING_POSTS_FOR_ARCHIVE = "FETCHING_POSTS_FOR_ARCHIVE";
export const FETCH_POSTS_FOR_ARCHIVE_SUCCESS =
  "FETCH_POSTS_FOR_ARCHIVE_SUCCESS";
export const FETCH_POSTS_FOR_ARCHIVE_FAILURE =
  "FETCH_POSTS_FOR_ARCHIVE_FAILURE";

// PROFILE ACTIONS
export const FETCHING_PROFILE_DATA = "FETCHING_PROFILE_DATA";
export const FETCH_PROFILE_DATA_SUCCESS = "FETCH_PROFILE_DATA_SUCCESS";
export const FETCH_PROFILE_DATA_FAILURE = "FETCH_PROFILE_DATA_FAILURE";

// SEARCH ACTIONS
export const FILTERING_POSTS = "FILTERING_POSTS";
export const FILTER_POSTS_SUCCESS = "FILTER_POSTS_SUCCESS";
export const FILTER_POSTS_FAILURE = "FILTER_POSTS_FAILURE";
export const GET_QUERY = "GET_QUERY";
export const CLOSE_MODAL = "CLOSE_MODAL";
