// AUTH ACTIONS
export const AUTHENTICATED = "AUTHENTICATED";
export const UNAUTHENTICATED = "UNAUTHENTICATED";
export const TESTING_TOKEN_REFRESH = "TESTING_TOKEN_REFRESH";

// CONTACTFORM ACTIONS
export const SUBMITTING_CONTACT_FORM = "SUBMITTING_CONTACT_FORM";
export const SUBMIT_CONTACT_FORM_SUCCESS = "SUBMIT_CONTACT_FORM_SUCCESS";
export const SUBMIT_CONTACT_FORM_FAILURE = "SUBMIT_CONTACT_FORM_FAILURE";

//NEWSLETTER ACTIONS
export const IS_SUBSCRIBING = "IS_SUBSCRIBING";
export const SUBSCRIBE_SUCCESS = "SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAILURE = "SUBSCRIBE_FAILURE";

// POST ACTIONS List
export const FETCHING_POSTS = "FETCHING_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const CLEAR_POSTS = "CLEAR_POSTS";

// POST ACTIONS Detail
export const FETCHING_POST = "FETCHING_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

// PROFILE ACTIONS
export const FETCHING_PROFILE_DATA = "FETCHING_PROFILE_DATA";
export const FETCH_PROFILE_DATA_SUCCESS = "FETCH_PROFILE_DATA_SUCCESS";
export const FETCH_PROFILE_DATA_FAILURE = "FETCH_PROFILE_DATA_FAILURE";

// SEARCH ACTIONS
export const FILTERING_POSTS = "FILTERING_POSTS";
export const FILTER_POSTS_SUCCESS = "FILTER_POSTS_SUCCESS";
export const FILTER_POSTS_FAILURE = "FILTER_POSTS_FAILURE";
export const GET_QUERY = "GET_QUERY";
export const CLOSE_MODAL = "CLOSE_MODAL";

// GOOGLE OAUTH2 ACTIONS
export const GOOG_IS_AUTHENTICATING = "GOOG_IS_AUTHENTICATING";
export const CONVERT_GOOG_TOKEN_SUCCESS = "CONVERT_GOOG_TOKEN_SUCCESS";
export const GOOGLE_LOGOUT = "GOOGLE_LOGOUT";
export const CONVERT_GOOG_TOKEN_FAILURE = "CONVERT_GOOG_TOKEN_FAILURE";

//CHANGE PASSWORD ACTIONS
export const IS_CHANGING_PASSWORD = "IS_CHANGING_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

//COMMENT LIST ACTIONS
export const IS_FETCHING_COMMENTS_FOR_POST = "IS_FETCHING_COMMENTS_FOR_POST";
export const FETCH_COMMENTS_FOR_POST_SUCCESS =
  "FETCH_COMMENTS_FOR_POST_SUCCESS";
export const FETCH_COMMENTS_FOR_POST_FAILURE =
  "FETCH_COMMENTS_FOR_POST_FAILURE";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

//VERIFY REGISTRATION EMAIL ACTIONS
export const VERIFY_REGISTRATION_EMAIL_SUCCESS =
  "VERIFY_REGISTRATION_EMAIL_SUCCESS";
export const VERIFY_REGISTRATION_EMAIL_FAILURE =
  "VERIFY_REGISTRATION_EMAIL_FAILURE";

//RESET PASSWORD ACTIONS
export const REQUEST_PASSWORD_RESET_SUCCESS = "REQUEST_PASSWORD_RESET_SUCCESS";
export const REQUEST_PASSWORD_RESET_FAILURE = "REQUEST_PASSWORD_RESET_FAILURE";
