# Generated by Django 2.0.2 on 2018-02-18 09:32

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[newsletter.models.email_validator])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
